# worker.default.yaml
# If you need any other external repository support, please place it in app/libs/external_repository
tools:
  python:
    setup:
  cpp:
    setup:
  lean:
    setup:
      - type: shell
        name: "create dir for external repository"
        run: |
          mkdir -p app/libs/external_repository 
      - type: shell
        name: "git clone external repository repl"
        run: |
          if [ -d "app/libs/external_repository/repl/.git" ]; then
            echo "[skip] repl already exists"
          else
            cd app/libs/external_repository/
            git clone --branch "v4.15.0" --single-branch --depth 1 "https://github.com/leanprover-community/repl.git" "repl"
          fi
      - type: shell
        name: "write dependency to lakefile.toml for repl"
        run: |
          cd app/libs/external_repository/repl
          echo '' >> lakefile.toml
          echo '[[require]]' >> lakefile.toml
          echo 'name = "mathlib"' >> lakefile.toml
          echo 'git = "https://github.com/leanprover-community/mathlib4.git"' >> lakefile.toml
          echo 'rev = "v4.15.0"' >> lakefile.toml
      - type: shell
        name: "build repl"
        run: |
          cd app/libs/external_repository/repl
          lake update
          lake build repl
